version: '3.7'

services:
  storages:
    image: mysql-redis
    build:
      context: .
    ports:
      - '3306:3306'
    expose:
      - 6379
    logging:
      options:
        max-size: "10m"
        max-file: "3"
    environment:
      TZ: Asia/Tokyo
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: hoge
